import { test, makeAccount, newSession, db } from "./helpers"
import fs from "fs"

// Not an assertion test: captures screenshots for visual review (SHOTS=1)
test.skip(!process.env.SHOTS, "set SHOTS=1")
const dir = process.env.SHOTS_DIR || "/tmp/shots"

test("screens", async ({ browser }) => {
  fs.mkdirSync(dir, { recursive: true })
  await db.liveRoom.updateMany({ where: { isActive: true }, data: { isActive: false, endedAt: new Date() } })
  const teacher = await makeAccount("TEACHER", { name: "Eğitmen Deniz" })
  const student = await makeAccount("STUDENT", { name: "Öğrenci Ayşe" })
  const { ctx: tctx, page: tp } = await newSession(browser, teacher.email)
  await tp.goto("/live/studio")
  await tp.getByTestId("go-live").waitFor({ state: "visible" })
  await tp.waitForTimeout(1500)
  await tp.screenshot({ path: `${dir}/studio-setup.png` })
  await tp.getByTestId("stream-title-input").fill("Sabah Yogası · Güneşe Selam")
  await tp.getByTestId("go-live").click()
  await tp.getByTestId("studio-live-badge").waitFor({ timeout: 30000 })
  const { ctx: sctx, page: sp } = await newSession(browser, student.email)
  await sp.goto("/live")
  await sp.waitForTimeout(1500)
  await sp.screenshot({ path: `${dir}/directory.png` })
  await sp.locator("a[data-testid=broadcast-card]").first().click()
  await sp.getByTestId("live-video").waitFor()
  await sp.waitForTimeout(4000)
  await sp.getByTestId("chat-input").fill("Günaydın hocam 🙏")
  await sp.getByTestId("chat-send").click()
  await tp.getByTestId("chat-input").fill("Günaydın, hoş geldin!")
  await tp.getByTestId("chat-send").click()
  await sp.waitForTimeout(1500)
  await sp.getByTestId("live-player").hover()
  await sp.getByTestId("quality-button").click()
  await sp.getByTestId("toggle-stats").click({ trial: false }).catch(() => {})
  await sp.waitForTimeout(1500)
  await sp.screenshot({ path: `${dir}/viewer.png` })
  await tp.getByRole("button", { name: /Denetim/ }).click()
  await tp.waitForTimeout(2500)
  await tp.screenshot({ path: `${dir}/studio-live.png` })
  await sp.setViewportSize({ width: 390, height: 844 })
  await sp.waitForTimeout(800)
  await sp.screenshot({ path: `${dir}/viewer-mobile.png` })
  tp.once("dialog", (d) => d.accept())
  await tp.getByTestId("end-stream").click()
  await sp.getByText("Yayın sona erdi").waitFor({ timeout: 20000 })
  await sp.screenshot({ path: `${dir}/ended.png` })
  await tctx.close(); await sctx.close()
})
